### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by mingridefeng** [iot-lab/iot-lab#266]
hello, I tried to do the [Radio monitoring for M3 nodes](https://www.iot-lab.info/tutorials/monitoring-radio-m3/) experiment, at the last step, I used Plot to check the picture, it seems there are some issues about enviroment seeting, 
ps: I used ssh -X 

my user name @grenoble:~$ plot_oml_radio -a -i ~/.iot-lab/169878/radio/m3_100.oml
/usr/local/lib/python2.7/dist-packages/oml_plot_tools/common.py:147: ConversionWarning: Some errors were detected !
    Line #91690 (got 3 columns instead of 7)
  invalid_raise=False)
Traceback (most recent call last):
  File "/usr/local/bin/plot_oml_radio", line 24, in <module>
    oml_plot_tools.radio.main()
  File "/usr/local/lib/python2.7/dist-packages/oml_plot_tools/radio.py", line 162, in main
    radio_plot(data, opts.title, selection)
  File "/usr/local/lib/python2.7/dist-packages/oml_plot_tools/radio.py", line 103, in radio_plot
    oml_plot_rssi(data, title)
  File "/usr/local/lib/python2.7/dist-packages/oml_plot_tools/radio.py", line 140, in oml_plot_rssi
    plt.figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1813, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by rienafairefr** [comment]
Hi,
not sure why this is complaining about $DISPLAY , I tried again with `ssh -X` and it didn't complain about $DISPLAY
I tried to plot this particular file, using `ssh -X`and it crashed the process, because the file is 150 MB.
You should download the OML file and plot on your own computer (apparently the resources of the SSH servers we provide is not enough)
